#!/usr/bin/env php
<?php
/**
 * Luminova Framework NovaKit Command Line Tool.
 * 
 * ██╗     ██╗   ██╗███╗   ███╗██╗███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ 
 * ██║     ██║   ██║████╗ ████║██║████╗  ██║██╔═══██╗██║   ██║██╔══██╗
 * ██║     ██║   ██║██╔████╔██║██║██╔██╗ ██║██║   ██║██║   ██║███████║
 * ██║     ██║   ██║██║╚██╔╝██║██║██║╚██╗██║██║   ██║██║   ██║██╔══██║
 * ███████╗╚██████╔╝██║ ╚═╝ ██║██║██║ ╚████║╚██████╔╝╚██████╔╝██║  ██║
 * ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝
 *
 * @package Luminova
 * @author Ujah Chigozie Peter
 * @copyright (c) Nanoblock Technology Ltd
 * @license See LICENSE file
 * @link https://luminova.ng
 */
use \Luminova\Command\Novakit;
use \Luminova\Boot;

// Autoload framework models
require __DIR__ . '/system/Boot.php';

// Bool novakit framework CLI configurations
Boot::cli();

// Ensure the current directory is pointing to the front controller's directory
chdir(DOCUMENT_ROOT);

// Initialize Novakit CLI Console and run command
(new Novakit())->run($_SERVER['argv'] ?? $argv ?? []);