#!/usr/bin/env php
<?php
/**
 * Luminova Framework
 *
 * @package Luminova
 * @author Ujah Chigozie Peter
 * @copyright (c) Nanoblock Technology Ltd
 * @license See LICENSE file
 */

/**
 * Location of the framework bootstrap file.
*/
use \Luminova\Command\Console;

/**
 * Autoload composers 
*/
require __DIR__ . '/bootstrap/cli.php';

/**
 * Ensure the current directory is pointing to the front controller's directory
*/
chdir(FRONT_CONTROLLER);

/**
 * Initialize Terminal Console and Run console instance
*/
(new Console())->run($_SERVER['argv'] ?? []);