#!/usr/bin/env php
<?php
/**
 * Luminova Framework Novakit Command Line Tool.
 * 
 * ██╗     ██╗   ██╗███╗   ███╗██╗███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ 
 * ██║     ██║   ██║████╗ ████║██║████╗  ██║██╔═══██╗██║   ██║██╔══██╗
 * ██║     ██║   ██║██╔████╔██║██║██╔██╗ ██║██║   ██║██║   ██║███████║
 * ██║     ██║   ██║██║╚██╔╝██║██║██║╚██╗██║██║   ██║██║   ██║██╔══██║
 * ███████╗╚██████╔╝██║ ╚═╝ ██║██║██║ ╚████║╚██████╔╝╚██████╔╝██║  ██║
 * ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝
 *
 * Bootstraps the CLI environment:
 *  - Handles background future child process worker {@see \Luminova\Component\Async::background()}.
 *  - Handles novakit and application commands.
 *
 * @package Luminova
 * @author Ujah Chigozie Peter
 * @copyright (c) Nanoblock Technology Ltd
 * @license See LICENSE file
 * @link https://luminova.ng
 */
use Luminova\Boot;
use Luminova\Command\Novakit;

// Autoload framework models
require __DIR__ . '/system/Boot.php';

// Register CLI initializations
Boot::cli();

// Pointing to project root
chdir(APP_ROOT);

// Run Novakit CLI Console or Background async task
Novakit::run($argv ?? []);