<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Luminova\\' => array($baseDir . '/system'),
    'App\\Controllers\\' => array($baseDir . '/app/Controllers'),
);
